export const GENRES = [
  { name: "Комедия", slug: "comedy" },
  { name: "Боевик", slug: "action" },
  { name: "Фантастика", slug: "sci-fi" },
  { name: "Триллер", slug: "thriller" },
  { name: "Приключения", slug: "adventure" },
  { name: "Драма", slug: "drama" },
  { name: "Мультфильм", slug: "animation" },
  { name: "Фэнтези", slug: "fantasy" },
  { name: "Семейный", slug: "family" },
  { name: "Мелодрама", slug: "romance" },
  { name: "Детектив", slug: "detective" },
  { name: "Музыка", slug: "music" },
  { name: "Биография", slug: "biography" },
  { name: "Военный", slug: "war" },
  { name: "Криминал", slug: "crime" },
  { name: "Ужасы", slug: "horror" },
  { name: "Исторический", slug: "history" },
  { name: "Вестерн", slug: "western" },
  { name: "Спорт", slug: "sport" },
];
